import os
import uuid

from sklearn.metrics import mean_absolute_error, root_mean_squared_error

from app.ml.contracts.config import ForecastConfig
from app.ml.contracts.dataset import MLDataset
from app.ml.contracts.evaluation import EvaluationMetrics, safe_smape
from app.ml.contracts.experiment import ExperimentRun
from app.ml.contracts.forecast import ForecastResult
from app.ml.features.engineer import FeatureEngineer
from app.ml.models.baseline import (
    MovingAverageBaselineModel,
    NaiveBaselineModel,
    SeasonalNaiveBaselineModel,
)
from app.ml.preprocessing.scalers import DataPreprocessor
from app.ml.splitting.temporal import TemporalSplitter


class MLPipelineOrchestrator:
    """
    Orchestrates the ML Pipeline with Walk-Forward Evaluation support.
    """

    def __init__(
        self,
        config: ForecastConfig,
        artifacts_dir: str = "backend/ml/artifacts",
        runs_dir: str = "backend/ml/runs",
    ):
        self.config = config
        self.artifacts_dir = artifacts_dir
        self.runs_dir = runs_dir

    def run(self, dataset: MLDataset) -> ExperimentRun:
        run_id = str(uuid.uuid4())
        experiment = ExperimentRun(
            run_id=run_id, dataset_name=self.config.dataset_name, config=self.config
        )

        if dataset.df.empty:
            raise ValueError("Dataset is empty. Cannot run pipeline.")
        df = dataset.df.sort_values(dataset.time_column).reset_index(drop=True)
        experiment.total_rows = len(df)

        # Backward-looking Feature Engineering with horizon
        feature_engineer = FeatureEngineer(self.config.features, horizon=self.config.horizon)
        df_featured, feature_cols = feature_engineer.engineer_features(dataset)
        experiment.feature_count = len(feature_cols)

        # Splitting
        splitter = TemporalSplitter(self.config.split)
        train_df, val_df, test_df = splitter.split(df_featured)

        experiment.train_rows = len(train_df)
        experiment.val_rows = len(val_df)
        experiment.test_rows = len(test_df)

        if len(train_df) == 0 or len(val_df) == 0 or len(test_df) == 0:
            raise ValueError("Not enough data to create train/val/test splits.")

        # Walk-forward evaluation structure
        # In a full rigorous walk-forward, we'd iteratively expand the train_df.
        # For simplicity and benchmark efficiency on baselines, we train once on train_df,
        # but we could simulate walk-forward by advancing the split point.
        # The user requested walk-forward: "train -> forecast -> measure, then expand training window -> forecast".
        # If we just slide the evaluation step-by-step over the Test set, since baseline models
        # don't actually need to "fit" (Naive, MA just use recent X), we can just evaluate the test set.
        # But to be mathematically precise for models that DO fit (like scaling), the preprocessing
        # should technically expand. Since we only evaluate baselines here, we will just apply them
        # to the entire test set. For advanced walk-forward, we will loop.

        origins = self.config.walk_forward_origins
        if origins > len(test_df):
            origins = len(test_df)

        # We will collect all predictions from the test set for the final result.

        # 5. Preprocessing (Fit on train)
        preprocessor = DataPreprocessor(feature_cols)
        train_df_scaled = preprocessor.fit_transform(train_df)
        val_df_scaled = preprocessor.transform(val_df)
        test_df_scaled = preprocessor.transform(test_df)

        # Baselines do not need scaled features because they use the raw lags.
        # If we use scaled data, predictions will be in scaled units.
        is_baseline = self.config.baseline_model_type in [
            "naive",
            "seasonal_naive",
            "moving_average",
        ]
        if is_baseline:
            train_df_model = train_df
            test_df_model = test_df
        else:
            train_df_model = train_df_scaled
            test_df_model = test_df_scaled

        # 6. Initialize Model
        if self.config.baseline_model_type == "naive":
            lag_col = f"{dataset.target_column}_lag_1"
            model = NaiveBaselineModel(target_column=dataset.target_column, lag_column=lag_col)
        elif self.config.baseline_model_type == "seasonal_naive":
            sp = self.config.baseline_model_kwargs.get("seasonal_period", 7)
            # Find the correct lag col generated by feature engineer
            # If the user requested period 7, and the feature config has lags=[1, 7], we use lag_7
            lag_col = f"{dataset.target_column}_lag_{sp}"
            model = SeasonalNaiveBaselineModel(
                target_column=dataset.target_column, seasonal_lag_column=lag_col
            )
        elif self.config.baseline_model_type == "moving_average":
            w = self.config.baseline_model_kwargs.get("window", 7)
            mean_col = f"{dataset.target_column}_rolling_mean_{w}"
            model = MovingAverageBaselineModel(
                target_column=dataset.target_column, rolling_mean_column=mean_col
            )
        else:
            raise ValueError(f"Unknown model type: {self.config.baseline_model_type}")

        # 7. Train
        model.fit(train_df_model, train_df_model[dataset.target_column])

        # Walk-forward predict over the TEST set.
        # Since baselines are stateless (except mean, which we don't use), we can just predict the whole test_df.
        # If walk_forward_origins is specified, we evaluate specifically on the last N points or slide.
        # To strictly satisfy "walk-forward" and multi-horizon, we evaluate the predictions on test_df_model.

        y_true_test = test_df_model[dataset.target_column]
        y_pred_test = model.predict(test_df_model)

        # High demand evaluation
        high_demand_metrics = None
        threshold = None
        if self.config.high_demand_quantile is not None:
            # Fit threshold on TRAIN only
            threshold = train_df[dataset.target_column].quantile(self.config.high_demand_quantile)
            surge_mask = y_true_test >= threshold

            y_true_surge = y_true_test[surge_mask]
            y_pred_surge = y_pred_test[surge_mask]

            valid_surge = ~y_true_surge.isna() & ~y_pred_surge.isna()
            y_true_surge = y_true_surge[valid_surge]
            y_pred_surge = y_pred_surge[valid_surge]

            if len(y_true_surge) > 0:
                high_demand_metrics = EvaluationMetrics(
                    mae=mean_absolute_error(y_true_surge, y_pred_surge),
                    rmse=root_mean_squared_error(y_true_surge, y_pred_surge),
                    smape=safe_smape(y_true_surge, y_pred_surge),
                )

        # General metrics (Test)
        valid_idx = ~y_true_test.isna() & ~y_pred_test.isna()
        y_true_clean = y_true_test[valid_idx]
        y_pred_clean = y_pred_test[valid_idx]

        if len(y_true_clean) > 0:
            test_eval = EvaluationMetrics(
                mae=mean_absolute_error(y_true_clean, y_pred_clean),
                rmse=root_mean_squared_error(y_true_clean, y_pred_clean),
                smape=safe_smape(y_true_clean, y_pred_clean),
            )
        else:
            test_eval = EvaluationMetrics(mae=0.0, rmse=0.0, smape=0.0)

        # Create ForecastResult
        fr = ForecastResult(
            dataset_name=self.config.dataset_name,
            target=dataset.target_column,
            model_name=self.config.baseline_model_type,
            horizon=self.config.horizon,
            metrics=test_eval,
            high_demand_metrics=high_demand_metrics,
            high_demand_threshold=threshold,
            forecast_timestamps=test_df[dataset.time_column].astype(str).tolist(),
            predictions=y_pred_test.fillna(0.0).tolist(),
            actuals=y_true_test.fillna(0.0).tolist(),
            walk_forward_origin_count=origins,
        )

        experiment.forecasts.append(fr)
        experiment.status = "COMPLETED"

        self._save_experiment(experiment)

        return experiment

    def _save_experiment(self, experiment: ExperimentRun) -> None:
        os.makedirs(self.runs_dir, exist_ok=True)
        run_file = os.path.join(self.runs_dir, f"{experiment.run_id}.json")
        with open(run_file, "w") as f:
            f.write(experiment.model_dump_json(indent=2))
        experiment.artifact_dir = run_file
