import pandas as pd

from app.ml.contracts.model import ForecastModel


class NaiveBaselineModel(ForecastModel):
    """
    Naive baseline model: y(t) = y(t-horizon)
    Since features are shifted by horizon, the lag_1 feature is exactly y(t-horizon).
    """

    def __init__(self, target_column: str, lag_column: str):
        self.target_column = target_column
        self.lag_column = lag_column  # e.g. "{target}_lag_1" which holds y(t-h)

    def fit(self, X_train: pd.DataFrame, y_train: pd.Series) -> None:
        pass

    def predict(self, X: pd.DataFrame) -> tuple[pd.Series, pd.Series | None, pd.Series | None]:
        if self.lag_column not in X.columns:
            raise ValueError(f"Lag column {self.lag_column} not found in features.")
        return X[self.lag_column].copy(), None, None


class SeasonalNaiveBaselineModel(ForecastModel):
    """
    Seasonal Naive baseline model: y(t) = y(t - m)
    Since the base shift is horizon, we need the feature that is shifted by the
    seasonal period relative to the forecast origin.
    Actually, to keep it simple and robust, the model can expect a specific lag column
    that corresponds to the seasonal period. For example, if we have weekly seasonality (7),
    and horizon=1, we need y(t-7). If horizon is already handled, we need a specific lag.
    To be safe, we just tell the model which column represents the seasonal lag.
    """

    def __init__(self, target_column: str, seasonal_lag_column: str):
        self.target_column = target_column
        self.seasonal_lag_column = seasonal_lag_column

    def fit(self, X_train: pd.DataFrame, y_train: pd.Series) -> None:
        pass

    def predict(self, X: pd.DataFrame) -> tuple[pd.Series, pd.Series | None, pd.Series | None]:
        if self.seasonal_lag_column not in X.columns:
            raise ValueError(
                f"Seasonal lag column {self.seasonal_lag_column} not found in features. Ensure it is generated by FeatureEngineer."
            )
        return X[self.seasonal_lag_column].copy(), None, None


class MovingAverageBaselineModel(ForecastModel):
    """
    Moving Average baseline model: predicts the rolling mean.
    Expects the FeatureEngineer to have generated a rolling mean column over the required window.
    """

    def __init__(self, target_column: str, rolling_mean_column: str):
        self.target_column = target_column
        self.rolling_mean_column = rolling_mean_column

    def fit(self, X_train: pd.DataFrame, y_train: pd.Series) -> None:
        pass

    def predict(self, X: pd.DataFrame) -> tuple[pd.Series, pd.Series | None, pd.Series | None]:
        if self.rolling_mean_column not in X.columns:
            raise ValueError(
                f"Rolling mean column {self.rolling_mean_column} not found in features. Ensure it is generated by FeatureEngineer."
            )
        return X[self.rolling_mean_column].copy(), None, None
